# Generated by Django 3.2.16 on 2022-11-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar'),
        ),
    ]
